---
common:
  mongo:
    uri: mongodb://mongo:27017
  production: false
  basic_auth:
    ladok: xyz
  tracing:
    addr: jaeger:4318
    type: jaeger
  queues:
    simple_queue:
      vc_persistent_save:
        name: vc_persistent_save
      vc_persistent_get:
        name: vc_persistent_get
      vc_persistent_delete:
        name: vc_persistent_delete
      vc_persistent_replace:
        name: vc_persistent_replace
  key_value:
    db: 3
    addr: redis:6379
    password: test-password
  qr:
    base_url: "https://deutsche-rentenversicherung.de"
    recovery_level: 2
    size: 256
  kafka:
    enabled: true

issuer:
  api_server:
    addr: :8080
  rpc_server:
    addr: :8090
  http_proxy:
  log:
    level:
  datastore:
    addr: datastore:8080

datastore:
  api_server:
    addr: :8080
  rpc_server:
    addr: datastore:8090

verifier:
  api_server:
    addr: :8080
  rpc_server:
    addr: verifier:8090

registry:
  api_server:
    addr: :8080
  smt:
    update_periodicity: 5
    init_leaf: 575cea4a-5725-11ee-8287-2b486b7ace28
  rpc_server:
    addr: registry:8090

persistent:
  api_server:
    addr: :8080

apigw:
  api_server:
    addr: :8080

mock_as:
  api_server:
    addr: :8080
  datastore_url: http://vc_dev_apigw:8080

ui:
  api_server:
    addr: :8080
  username: "admin"
  password: "secret123"
  #It is recommended to use an authentication key with 32 or 64 bytes.
  session_cookie_authentication_key: "PjanW5cOBIlWzjLK23Q8NIo4va53e1bsgWmcqMdznVzkW3uEozfotj7MZsD7HpBo"
  #The encryption key, must be either 16, 24, or 32 bytes to select AES-128, AES-192, or AES-256 modes.
  session_store_encryption_key: "SQxqb3LKw1YFyAiy4j7FaGGJKeEzr8Db"
  services:
    apigw:
      base_url: http://vc_dev_apigw:8080
    mockas:
      base_url: http://vc_dev_mockas:8080
